/**
 * Design tokens ported 1:1 from the Stitch mockups
 * (stitch/stitch_hopss_electronic_incident_management_system/*\/code.html
 * inline `tailwind.config` script) so Stitch markup can be carried into Vue
 * components without renaming utility classes. See
 * stitch/.../institutional_clinical_vanguard/DESIGN.md for the human-readable
 * semantic names behind these Material-You-style tokens, e.g.:
 *   primary            -> "Deep Clinical Navy"   #1E3A8A (primary-container here)
 *   secondary          -> "Clinical Teal"        #0D9488 / accent #14B8A6
 *   error              -> "Emergency Crimson"    #DC2626
 *   surface-container* -> neutral card/canvas tiers
 */
/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    theme: {
        extend: {
            colors: {
                'on-secondary-container': '#006f66',
                secondary: '#006a61',
                'surface-dim': '#d2d9f4',
                'on-tertiary-fixed-variant': '#004b73',
                'on-primary-container': '#90a8ff',
                'on-tertiary-fixed': '#001d31',
                'surface-container': '#eaedff',
                'on-secondary-fixed': '#00201d',
                'on-primary-fixed-variant': '#264191',
                'surface-container-highest': '#dae2fd',
                background: '#faf8ff',
                'on-background': '#131b2e',
                outline: '#757682',
                'surface-bright': '#faf8ff',
                'primary-fixed-dim': '#b6c4ff',
                'secondary-fixed': '#89f5e7',
                'inverse-surface': '#283044',
                'tertiary-fixed-dim': '#93ccff',
                'inverse-on-surface': '#eef0ff',
                primary: '#00236f',
                'secondary-container': '#86f2e4',
                'tertiary-fixed': '#cce5ff',
                tertiary: '#002d48',
                'tertiary-container': '#004469',
                surface: '#faf8ff',
                'surface-container-lowest': '#ffffff',
                'on-primary-fixed': '#00164e',
                'on-secondary-fixed-variant': '#005049',
                'primary-fixed': '#dce1ff',
                'surface-container-high': '#e2e7ff',
                'primary-container': '#1e3a8a',
                'on-error-container': '#93000a',
                'on-error': '#ffffff',
                'secondary-fixed-dim': '#6bd8cb',
                'error-container': '#ffdad6',
                'on-secondary': '#ffffff',
                'on-tertiary': '#ffffff',
                'on-tertiary-container': '#56b3f9',
                'inverse-primary': '#b6c4ff',
                'on-surface-variant': '#444651',
                'on-primary': '#ffffff',
                'surface-tint': '#4059aa',
                error: '#ba1a1a',
                'surface-variant': '#dae2fd',
                'on-surface': '#131b2e',
                'surface-container-low': '#f2f3ff',
                'outline-variant': '#c5c5d3',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                gutter: '1.5rem',
                'margin-mobile': '1rem',
                'space-md': '1rem',
                'gutter-mobile': '1rem',
                'space-lg': '1.5rem',
                margin: '2rem',
                'space-xs': '0.25rem',
                'space-xl': '2rem',
                'space-sm': '0.5rem',
            },
            fontFamily: {
                'code-tabular': ['Inter'],
                'headline-md': ['Plus Jakarta Sans'],
                'title-md': ['Inter'],
                'headline-xl-mobile': ['Plus Jakarta Sans'],
                'headline-sm': ['Plus Jakarta Sans'],
                'headline-lg-mobile': ['Plus Jakarta Sans'],
                'headline-lg': ['Plus Jakarta Sans'],
                'headline-xl': ['Plus Jakarta Sans'],
                'label-sm': ['Inter'],
                'body-lg': ['Inter'],
                'label-md': ['Inter'],
                'body-sm': ['Inter'],
                'title-lg': ['Inter'],
                'body-md': ['Inter'],
                'title-sm': ['Inter'],
            },
            fontSize: {
                'code-tabular': ['0.8125rem', { lineHeight: '1.125rem', letterSpacing: '0em', fontWeight: '500' }],
                'headline-md': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.015em', fontWeight: '600' }],
                'title-md': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '600' }],
                'headline-xl-mobile': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-sm': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-lg-mobile': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.015em', fontWeight: '600' }],
                'headline-lg': ['1.875rem', { lineHeight: '2.25rem', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-xl': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.025em', fontWeight: '700' }],
                'label-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.05em', fontWeight: '600' }],
                'body-lg': ['1rem', { lineHeight: '1.625rem', letterSpacing: '0em', fontWeight: '400' }],
                'label-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '500' }],
                'body-sm': ['0.75rem', { lineHeight: '1.125rem', letterSpacing: '0.01em', fontWeight: '400' }],
                'title-lg': ['1.125rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '600' }],
                'body-md': ['0.875rem', { lineHeight: '1.375rem', letterSpacing: '0em', fontWeight: '400' }],
                'title-sm': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.005em', fontWeight: '600' }],
            },
        },
    },
    plugins: [],
};
